name: Unittests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Running unit tests
      run: |
        python ./tests/main.py
    - name: Running on self
      run: |
        python -m pyrefact . --preserve .
    - name: Install as editable
      run: |
        pip install -e .
    - name: Rerun unit tests
      run: |
        python ./tests/main.py
